name:                focus
version:             0.1.0.0
github:              "ChrisPenner/focus"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ChrisPenner/focus#readme>

default-extensions:
- FlexibleInstances
- FlexibleContexts
- ScopedTypeVariables
- LambdaCase
- ViewPatterns
- TypeApplications
- TypeOperators
- DeriveFunctor
- DeriveTraversable
- DeriveGeneric
- DerivingStrategies
- StandaloneDeriving
- TemplateHaskell
- RankNTypes
- GADTs
- MultiParamTypeClasses
- OverloadedStrings
- BlockArguments
- InstanceSigs
- NamedFieldPuns
- ImportQualifiedPost
- KindSignatures

dependencies:
- base >= 4.7 && < 5
- lens
- lens-action
- text
- unliftio
- bytestring
- vector
- optparse-applicative
- megaparsec
- lens-regex-pcre
- pcre-heavy
- recursion-schemes
- some
- mtl
- diagnose
- deriving-compat
- prettyprinter-ansi-terminal
- unification-fd
- transformers

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  focus:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - focus
